# Generated by Django 4.0.6 on 2022-07-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0006_stockhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
